### ISSUE TITLE
Change base.yml main keys to be package manager (or other identifiable binary) names rather than repo-tags

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#61]
The repo-tag is a container registry construct and could change depending on the registry. So look up the base commands based on the package manager rather than the repo tag.

Eg:
```
vmware/photon:
  latest: '1.0'
  tags:
    '1.0':
      shell: '/usr/bin/bash'
      names:
```
to

```
tdnf:
  repo: 'vmware/photon'
  tags: ['latest', '1.0']
  shell: '/usr/bin/bash'
  names:
```
This is to support #51
